server:
  port: ${PORT:7005}

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:7004}/${DATABASE:common_user}?currentSchema=${DB_SCHEMA:canyon}
    username: ${DB_USER:devwikiuser}
    password: ${DB_PASSWORD:SECURED}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    show-sql: true
debug: true

management:
  endpoints:
    web:
      base-path: /common/user
      exposure:
        include: 'health'