
services:
  krakend-gateway:
    build: 'krakend-gateway/krakend'
    image: 'krakend-gateway:latest'
    ports:
      - '8000:8000'
  common-oauth-redis:
    image: 'redis:6.0.20-alpine3.18'
    command: redis-server --protected-mode no --requirepass SECURED
  common-oauth:
    build: 'oauth'
    image: 'common-oauth:latest'
    environment:
      - 'REDIS_PORT=6379'
      - 'REDIS_HOST=common-oauth-redis'
      - 'SVC_COMMON_USER=common-user'
      - 'LOOT_LOGGING_LEVEL=debug'
    depends_on:
      - common-oauth-redis
  common-user-postgres:
    build: 'user/postgres'
    image: 'user-postgres:latest'
  common-user:
    build: 'user'
    image: 'common-user:latest'
    environment:
      - 'DB_URL=common-user-postgres'
      - 'DB_PORT=5432'
      - 'LOOT_LOGGING_LEVEL=debug'
    depends_on:
      - common-user-postgres
  sample-resource-server:
    build: 'sample-resource-server'
    image: 'sample-resource-server:latest'
    environment:
      - 'LOOT_LOGGING_LEVEL=debug'