###
POST http://localhost:8000/common/auth/authenticate
Accept: application/json
Content-Type: application/json

{
  "loginId": "john.doe@gmail.com",
  "password": "password"
}

###
GET http://localhost:8000/resource
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJOYjMyTVZPaHpvcERRSFQzU0I0TmFlOVlZV2VoREpzY3FteUZrVlhSa202alRQMWY0WlYzUE0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2huLmRvZUBnbWFpbC5jb20iLCJyb2xlcyI6W3sicm9sZUlkIjoxLCJuYW1lIjoiQURNSU4iLCJwZXJtaXNzaW9uU2V0IjpbeyJwZXJtaXNzaW9uSWQiOjMsIm5hbWUiOiJERUxFVEVfQUxMIn0seyJwZXJtaXNzaW9uSWQiOjIsIm5hbWUiOiJXUklURV9BTEwifSx7InBlcm1pc3Npb25JZCI6MSwibmFtZSI6IlJFQURfQUxMIn1dfV0sImlzcyI6ImRldndpa2kub25saW5lIiwiZXhwIjoxNzc2NDk4ODU3LCJhY2NvdW50VmVyaWZpZWQiOnRydWUsInN0YXR1cyI6IkFDVElWRSIsInVzZXJuYW1lIjoiSm9obiBEb2UifQ.cWFzz9He8c8wS6oMgyfHlTYo5AzOzZlw5N5rVTbULvlMNp0hY0DX4yO5i0WcDnkgbxYV4Dq77DOjpc0-l9lWToBXOFgAdga8dJUTz4OYGowIRCjhMZ-96Y8KfY09UERb0Fb2Duu1PtKuPj51vwvQn830rqMk1RxOiwbrJxYaxaBfz763UxbjDBfGyybYAb7mJkagQOLh3KZjGkF8BjnBjYvhm3TZmgdW57roDgTNRY6BBRMqEmJgvaYqW1KJI-nI9SrOf6V8oc_3HT-nL9jJomwnoBAVeYJVNLj-DHACbJPKzh1iaSzN6CFiwSOiUowihwFkY1IcHkhdMXXrOa-qeQ