###
POST http://localhost:7008/api/v1/auth/authenticate
Accept: application/json
Content-Type: application/json

{
  "loginId": "john.doe@gmail.com",
  "password": "password"
}

###
POST http://localhost:7008/api/v1/auth/refresh-token
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJOYjMyTVZPaHpvcERRSFQzU0I0TmFlOVlZV2VoREpzY3FteUZrVlhSa202alRQMWY0WlYzUE0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2huLmRvZUBnbWFpbC5jb20iLCJyb2xlcyI6W3sicm9sZUlkIjoxLCJuYW1lIjoiQURNSU4iLCJwZXJtaXNzaW9uU2V0IjpbeyJwZXJtaXNzaW9uSWQiOjEsIm5hbWUiOiJSRUFEX0FMTCJ9LHsicGVybWlzc2lvbklkIjozLCJuYW1lIjoiREVMRVRFX0FMTCJ9LHsicGVybWlzc2lvbklkIjoyLCJuYW1lIjoiV1JJVEVfQUxMIn1dfV0sImlzcyI6ImRldndpa2kub25saW5lIiwiZXhwIjoxNzc2NDk4Njk5LCJhY2NvdW50VmVyaWZpZWQiOnRydWUsInN0YXR1cyI6IkFDVElWRSIsInVzZXJuYW1lIjoiSm9obiBEb2UifQ.MemMDhHMlRr_K_7Gwr1Qev1FOMvJU9yaViO19c69t-f0meD-CTNv4LXrw5f6fvJzx5brsiH2QYXc_4Fg2CccpED6vlOmf9dZCtToAQ7EDIyGg5wZDmUHlxMOXylR8q9w_AqK0p-2RmQp2HukcOPIIuTdjydO64ZGr_0zyjv4Zr3ufP1hVghTjNgLjgkN804wTF2sC3PEbtHuNpGgUgGBfvylsKbtL9O_l0ji3ddnxGDpnTIKifTugQiYgFhoipWwB9pvKShevo9D6FKg7Tfd1jGLXwLbzlahn_FbxtvdD8kWf3kFcOzJ5Egq9vb7l7zC-aRl4-aD34olhDgYtXDKKQ